#!/usr/bin/env python3
"""Optimizer pipeline: propose -> apply -> render -> gate -> accept/reject rollback."""

from __future__ import annotations

import argparse
import copy
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from prompts import OPTIMIZER_SYSTEM_PROMPT, OPTIMIZER_USER_TEMPLATE


def parse_args():
    p = argparse.ArgumentParser(description="UT Optimizer Agent")
    p.add_argument("--report", required=True, help="coverage_report.json path")
    p.add_argument("--feedback", required=True, help="feedback.json path")
    p.add_argument("--skill-pack", required=True, help="skill_pack.json path")
    p.add_argument("--skill-output", required=True, help="Rendered SKILL.md output path")
    p.add_argument("--round", type=int, default=1, help="Current optimization round")
    p.add_argument("--gate-cmd", default="", help="Optional gate evaluation command")
    p.add_argument("--gate-report", default="", help="Coverage report generated by gate-cmd")
    p.add_argument(
        "--branch-drop-tolerance",
        type=float,
        default=0.2,
        help="Reject when after_branch + tolerance < before_branch",
    )
    p.add_argument(
        "--pass-rate-drop-tolerance",
        type=float,
        default=3.0,
        help="Reject when after_pass_rate + tolerance < before_pass_rate",
    )
    p.add_argument("--result", default="", help="Where to write optimization result json")
    p.add_argument(
        "--max-step-changes",
        type=int,
        default=2,
        help="Maximum number of skill parameters to adjust per round (1-2 recommended)",
    )
    # LLM optimizer args
    p.add_argument("--model", default="deepseek/deepseek-chat", help="LLM model for optimizer")
    p.add_argument("--use-llm", dest="use_llm", action="store_true", default=True, help="Enable LLM optimizer")
    p.add_argument("--no-llm", dest="use_llm", action="store_false", help="Disable LLM, use rules only")
    p.add_argument("--principles-dir", default="", help="Directory containing per-project principles (results/principles/)")
    p.add_argument("--project-name", default="", help="Current project name (for principle isolation)")
    return p.parse_args()


def get_total(report: dict) -> dict:
    if isinstance(report.get("_total"), dict):
        return report["_total"]
    coverage = report.get("coverage", {})
    return {
        "line": coverage.get("line", {}).get("pct", 0.0),
        "branch": coverage.get("branch", {}).get("pct", 0.0),
        "method": coverage.get("method", {}).get("pct", 0.0),
    }


def classify_risk(parameter_changes: list) -> tuple[str, list[str]]:
    if not parameter_changes:
        return "low", ["no parameter change applied"]

    risk_score = 0
    reasons = []
    if len(parameter_changes) >= 2:
        risk_score = max(risk_score, 1)
        reasons.append("two parameters changed in one round")
    if any(ch.get("param", "").startswith("generation.") for ch in parameter_changes):
        risk_score = max(risk_score, 1)
        reasons.append("generation knobs may increase test volume and noise")
    if any(ch.get("param", "").startswith("targets.") for ch in parameter_changes):
        risk_score = max(risk_score, 2)
        reasons.append("target threshold changes affect optimization objective directly")

    level = "high" if risk_score >= 2 else "medium" if risk_score == 1 else "low"
    return level, reasons


def summarize_expected_benefit(parameter_changes: list) -> str:
    params = {ch.get("param", "") for ch in parameter_changes}
    focus = []
    if "generation.min_cases_per_method" in params or "rules.branch_focus" in params:
        focus.append("raise branch path hit probability")
    if "rules.boundary_three_point" in params:
        focus.append("improve line coverage on structural edge inputs")
    if "rules.quality" in params:
        focus.append("improve method-level invocation completeness")
    if not focus:
        return "No expected gain because no parameter was changed."
    return "Expected benefit: " + "; ".join(focus) + "."


# ---------------------------------------------------------------------------
# Rule-based proposal (original logic, renamed)
# ---------------------------------------------------------------------------

def build_proposal_rules(report: dict, feedback: dict, pack: dict, round_num: int, max_step_changes: int = 2) -> dict:
    total = get_total(report)
    method_gaps = feedback.get("method_gaps", [])
    weak_methods = method_gaps[:8]
    step_limit = max(1, min(2, int(max_step_changes)))

    proposal = {
        "round": round_num,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "before_total": total,
        "changes": [],
        "max_step_changes": step_limit,
        "parameter_changes": [],
        "skipped_candidates": [],
        "focus_hints": [f"{x['class']}.{x['method']} branch={x['branch']}%" for x in weak_methods],
        "method": "rules",
    }

    generation = copy.deepcopy(pack.get("generation", {}))
    rules = copy.deepcopy(pack.get("rules", {}))
    targets = copy.deepcopy(pack.get("targets", {}))

    def try_change(param: str, before_value, after_value, message: str, expected_benefit: str) -> bool:
        if len(proposal["parameter_changes"]) >= step_limit:
            proposal["skipped_candidates"].append({"param": param, "reason": "step_limit_reached"})
            return False
        if before_value == after_value:
            proposal["skipped_candidates"].append({"param": param, "reason": "no_effect"})
            return False
        proposal["parameter_changes"].append(
            {
                "param": param,
                "before": before_value,
                "after": after_value,
                "expected_benefit": expected_benefit,
            }
        )
        proposal["changes"].append(message)
        return True

    if total.get("branch", 0.0) < targets.get("branch_pct", 85.0):
        current = int(generation.get("min_cases_per_method", 3))
        updated = min(6, current + 1)
        if try_change(
            "generation.min_cases_per_method",
            current,
            updated,
            f"increase generation.min_cases_per_method: {current} -> {updated}",
            "more candidate test cases per method can improve branch exploration",
        ):
            generation["min_cases_per_method"] = updated

        branch_focus = list(rules.get("branch_focus", []))
        hint = "for every uncovered branch, add at least one branch-forcing test input"
        if hint in branch_focus:
            proposal["skipped_candidates"].append({"param": "rules.branch_focus", "reason": "hint_already_present"})
        else:
            before = len(branch_focus)
            branch_focus.append(hint)
            if try_change(
                "rules.branch_focus",
                before,
                len(branch_focus),
                "append rules.branch_focus hint for branch-forcing inputs",
                "explicit branch-forcing hints can target missed condition paths",
            ):
                rules["branch_focus"] = branch_focus

    if total.get("line", 0.0) < targets.get("line_pct", 90.0):
        boundary = list(rules.get("boundary_three_point", []))
        hint = "for string and collection APIs, include null, empty, singleton, and oversized inputs"
        if hint in boundary:
            proposal["skipped_candidates"].append({"param": "rules.boundary_three_point", "reason": "hint_already_present"})
        else:
            before = len(boundary)
            boundary.append(hint)
            if try_change(
                "rules.boundary_three_point",
                before,
                len(boundary),
                "append rules.boundary_three_point hint for structural edge cases",
                "boundary-focused templates can expose uncovered lines around input checks",
            ):
                rules["boundary_three_point"] = boundary

    if total.get("method", 0.0) < targets.get("method_pct", 85.0):
        quality = list(rules.get("quality", []))
        hint = "ensure every public method appears in at least one explicit test name"
        if hint in quality:
            proposal["skipped_candidates"].append({"param": "rules.quality", "reason": "hint_already_present"})
        else:
            before = len(quality)
            quality.append(hint)
            if try_change(
                "rules.quality",
                before,
                len(quality),
                "append rules.quality hint for method-level coverage",
                "method-name inclusion guidance reduces missed public API methods",
            ):
                rules["quality"] = quality

    if not proposal["parameter_changes"]:
        proposal["changes"].append("no-op: no eligible parameter update under current constraints")

    risk_level, risk_reasons = classify_risk(proposal["parameter_changes"])
    proposal["risk_level"] = risk_level
    proposal["risk_reasons"] = risk_reasons
    proposal["expected_benefit"] = summarize_expected_benefit(proposal["parameter_changes"])

    if risk_level != "low":
        proposal["changes"].append(f"risk_assessment={risk_level}: " + "; ".join(risk_reasons))

    next_pack = copy.deepcopy(pack)
    next_pack["generation"] = generation
    next_pack["rules"] = rules
    next_pack["focus_hints"] = proposal["focus_hints"]
    next_pack["version"] = f"v3.{round_num}"
    return proposal, next_pack


# ---------------------------------------------------------------------------
# LLM-based proposal
# ---------------------------------------------------------------------------

EVOLUTION_LOG = "results/evolution_log.json"
REQUIRED_PACK_KEYS = {"version", "targets", "generation", "rules"}
REQUIRED_RULES_KEYS = {"branch_focus", "boundary_three_point", "loop_paths", "condition_matrix", "exception_policy", "quality"}
MAX_RULES_PER_CATEGORY = 15


def build_optimizer_prompt(
    pack: dict,
    feedback: dict,
    evolution_entries: list,
    principles: list,
    round_num: int,
    max_changes: int = 2,
) -> tuple[str, str]:
    system = OPTIMIZER_SYSTEM_PROMPT.format(max_changes=max_changes, round_num=round_num)

    # Evolution history text
    if evolution_entries:
        history_lines = []
        for e in evolution_entries:
            cov = e.get("coverage_before", {})
            b = cov.get("branch", "?")
            changes = e.get("changes_made", "?")
            history_lines.append(f"- iter {e.get('iter', '?')}: branch={b}%, changes={changes}")
        evolution_text = "\n".join(history_lines)
    else:
        evolution_text = "(no prior rounds)"

    # Principles text
    if principles:
        prin_lines = []
        for p in principles[:15]:
            ptype = p.get("type", "unknown")
            summary = p.get("change_summary", "?")
            delta = p.get("coverage_delta", {})
            conf = p.get("confidence", 0)
            project = p.get("project", "?")
            prin_lines.append(f"- [{ptype}] ({project}) {summary} (branch_delta={delta.get('branch', 0):+.1f}%, confidence={conf:.2f})")
        principles_text = "\n".join(prin_lines)
    else:
        principles_text = "(no principles yet)"

    # Trim feedback to essential fields
    feedback_slim = {
        "method_gaps": feedback.get("method_gaps", [])[:15],
        "failure_taxonomy": feedback.get("failure_taxonomy", {}),
    }

    user = OPTIMIZER_USER_TEMPLATE.format(
        skill_pack_json=json.dumps(pack, indent=2, ensure_ascii=False),
        feedback_json=json.dumps(feedback_slim, indent=2, ensure_ascii=False),
        history_count=len(evolution_entries),
        evolution_history=evolution_text,
        principles_text=principles_text,
    )
    return system, user


def call_llm_optimizer(system: str, user: str, model: str, cwd: Path) -> str | None:
    prompt = f"<system>\n{system}\n</system>\n\n{user}"
    args = ["opencode", "run", prompt, "-m", model]
    try:
        result = subprocess.run(
            args,
            cwd=str(cwd),
            check=False,
            text=True,
            capture_output=True,
            timeout=120,
        )
        if result.returncode != 0:
            print(f"[optimizer] LLM call failed: exit_code={result.returncode}")
            if result.stderr:
                for line in result.stderr.strip().splitlines()[:5]:
                    print(f"[optimizer]   {line}")
            return None
        return result.stdout
    except subprocess.TimeoutExpired:
        print("[optimizer] LLM call timed out (120s)")
        return None
    except Exception as exc:
        print(f"[optimizer] LLM call error: {exc}")
        return None


def extract_json_from_response(text: str) -> dict | None:
    # Try ```json fenced block first
    match = re.search(r"```json\s*\n(.*?)```", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    # Try any ``` fenced block
    match = re.search(r"```\s*\n(.*?)```", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    # Try bare JSON (find first { to last })
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            pass

    return None


def validate_skill_pack(candidate: dict, original: dict) -> list[str]:
    errors = []

    # Check required top-level keys
    missing = REQUIRED_PACK_KEYS - set(candidate.keys())
    if missing:
        errors.append(f"missing top-level keys: {missing}")

    # Check targets not lowered
    orig_targets = original.get("targets", {})
    cand_targets = candidate.get("targets", {})
    for key in ("line_pct", "branch_pct", "method_pct"):
        orig_val = orig_targets.get(key, 0)
        cand_val = cand_targets.get(key, 0)
        if isinstance(cand_val, (int, float)) and cand_val < orig_val:
            errors.append(f"target {key} lowered: {orig_val} -> {cand_val}")

    # Check rules structure
    cand_rules = candidate.get("rules", {})
    if not isinstance(cand_rules, dict):
        errors.append("rules is not a dict")
    else:
        missing_rules = REQUIRED_RULES_KEYS - set(cand_rules.keys())
        if missing_rules:
            errors.append(f"missing rule categories: {missing_rules}")
        for cat, items in cand_rules.items():
            if not isinstance(items, list):
                errors.append(f"rules.{cat} is not a list")
            elif len(items) > MAX_RULES_PER_CATEGORY:
                errors.append(f"rules.{cat} has {len(items)} items (max {MAX_RULES_PER_CATEGORY})")

    # Check generation structure
    cand_gen = candidate.get("generation", {})
    if not isinstance(cand_gen, dict):
        errors.append("generation is not a dict")

    return errors


def diff_skill_packs(old: dict, new: dict) -> list[dict]:
    changes = []

    def _compare(prefix: str, o, n):
        if isinstance(o, dict) and isinstance(n, dict):
            all_keys = set(o.keys()) | set(n.keys())
            for k in sorted(all_keys):
                _compare(f"{prefix}.{k}" if prefix else k, o.get(k), n.get(k))
        elif isinstance(o, list) and isinstance(n, list):
            if o != n:
                changes.append({
                    "param": prefix,
                    "before": o,
                    "after": n,
                    "expected_benefit": "LLM-proposed change",
                })
        elif o != n:
            changes.append({
                "param": prefix,
                "before": o,
                "after": n,
                "expected_benefit": "LLM-proposed change",
            })

    _compare("", old, new)
    return changes


def load_all_principles(principles_dir: str, limit: int = 15) -> list[dict]:
    """Load and merge principles from all project files in the directory."""
    if not principles_dir:
        return []
    pdir = Path(principles_dir)
    if not pdir.is_dir():
        return []
    all_principles = []
    for f in sorted(pdir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
            for p in data.get("principles", []):
                p.setdefault("project", f.stem)
                all_principles.append(p)
        except (json.JSONDecodeError, OSError):
            continue
    # Sort by timestamp descending, take most recent
    all_principles.sort(key=lambda x: x.get("timestamp", ""), reverse=True)
    return all_principles[:limit]


def build_proposal_llm(
    report: dict,
    feedback: dict,
    pack: dict,
    round_num: int,
    model: str,
    principles_dir: str,
    cwd: Path,
    max_step_changes: int = 2,
) -> tuple[dict, dict] | None:
    # Load evolution log
    evo_path = cwd / EVOLUTION_LOG
    evolution_entries = []
    if evo_path.exists():
        try:
            evo_log = json.loads(evo_path.read_text(encoding="utf-8"))
            evolution_entries = evo_log.get("entries", [])[-5:]
        except (json.JSONDecodeError, OSError):
            pass

    # Load principles from all projects
    principles = load_all_principles(principles_dir)

    system, user = build_optimizer_prompt(pack, feedback, evolution_entries, principles, round_num, max_step_changes)

    raw = call_llm_optimizer(system, user, model, cwd)
    if raw is None:
        return None

    candidate = extract_json_from_response(raw)
    if candidate is None:
        # Retry once with a fix prompt
        print("[optimizer] LLM output had no valid JSON, retrying with fix prompt...")
        fix_prompt = (
            "Your previous response did not contain valid JSON. "
            "Please output ONLY the complete skill_pack.json inside a ```json block. No other text."
        )
        raw2 = call_llm_optimizer(system, fix_prompt, model, cwd)
        if raw2 is not None:
            candidate = extract_json_from_response(raw2)
        if candidate is None:
            print("[optimizer] LLM retry also failed to produce valid JSON")
            return None

    errors = validate_skill_pack(candidate, pack)
    if errors:
        print(f"[optimizer] LLM proposal validation failed: {errors}")
        # Retry once
        fix_prompt = (
            f"Your proposed skill_pack.json has validation errors:\n"
            + "\n".join(f"- {e}" for e in errors)
            + "\n\nPlease fix these issues and output the corrected complete JSON in a ```json block."
        )
        raw2 = call_llm_optimizer(system, fix_prompt, model, cwd)
        if raw2 is not None:
            candidate = extract_json_from_response(raw2)
            if candidate is not None:
                errors = validate_skill_pack(candidate, pack)
        if errors:
            print(f"[optimizer] LLM retry still has validation errors: {errors}")
            return None

    parameter_changes = diff_skill_packs(pack, candidate)
    total = get_total(report)
    method_gaps = feedback.get("method_gaps", [])
    weak_methods = method_gaps[:8]

    # Extract reasoning from LLM response
    reasoning = ""
    reasoning_match = re.search(r"##\s*Reasoning\s*\n(.*)", raw, re.DOTALL)
    if reasoning_match:
        reasoning = reasoning_match.group(1).strip()[:500]

    proposal = {
        "round": round_num,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "before_total": total,
        "changes": [ch["param"] + ": changed" for ch in parameter_changes[:10]],
        "max_step_changes": max_step_changes,
        "parameter_changes": parameter_changes,
        "skipped_candidates": [],
        "focus_hints": [f"{x['class']}.{x['method']} branch={x['branch']}%" for x in weak_methods],
        "method": "llm",
        "reasoning": reasoning,
    }

    risk_level, risk_reasons = classify_risk(parameter_changes)
    proposal["risk_level"] = risk_level
    proposal["risk_reasons"] = risk_reasons
    proposal["expected_benefit"] = reasoning[:200] if reasoning else "LLM-proposed optimization"

    if risk_level != "low":
        proposal["changes"].append(f"risk_assessment={risk_level}: " + "; ".join(risk_reasons))

    # Ensure version is set
    candidate.setdefault("version", f"v3.{round_num}")
    candidate.setdefault("focus_hints", proposal["focus_hints"])

    return proposal, candidate


# ---------------------------------------------------------------------------
# Unified entry point
# ---------------------------------------------------------------------------

def build_proposal(
    report: dict,
    feedback: dict,
    pack: dict,
    round_num: int,
    max_step_changes: int = 2,
    use_llm: bool = True,
    model: str = "deepseek/deepseek-chat",
    principles_dir: str = "",
    cwd: Path | None = None,
) -> tuple[dict, dict]:
    if use_llm:
        if cwd is None:
            cwd = Path(__file__).resolve().parent.parent
        result = build_proposal_llm(
            report, feedback, pack, round_num,
            model=model,
            principles_dir=principles_dir,
            cwd=cwd,
            max_step_changes=max_step_changes,
        )
        if result is not None:
            print("[optimizer] LLM proposal generated successfully")
            return result
        print("[optimizer] LLM failed, falling back to rules")
    return build_proposal_rules(report, feedback, pack, round_num, max_step_changes)


# ---------------------------------------------------------------------------
# Principle distillation
# ---------------------------------------------------------------------------

def distill_principle(
    proposal: dict,
    decision: str,
    before_total: dict,
    after_total: dict,
    feedback: dict,
    round_num: int,
    principles_dir: str,
    project_name: str,
) -> None:
    if not principles_dir or not project_name:
        return

    principles_path = Path(principles_dir) / f"{project_name}.json"

    # Load existing
    principles = []
    if principles_path.exists():
        try:
            data = json.loads(principles_path.read_text(encoding="utf-8"))
            principles = data.get("principles", [])
        except (json.JSONDecodeError, OSError):
            pass

    # Compute coverage delta
    line_delta = float(after_total.get("line", 0)) - float(before_total.get("line", 0))
    branch_delta = float(after_total.get("branch", 0)) - float(before_total.get("branch", 0))
    method_delta = float(after_total.get("method", 0)) - float(before_total.get("method", 0))

    # Determine type
    is_accepted = decision == "accepted"
    principle_type = "guiding" if is_accepted else "cautionary"

    # Change summary
    changes = proposal.get("changes", [])
    change_summary = "; ".join(changes[:3]) if changes else "no changes"

    # Affected methods from feedback
    method_gaps = feedback.get("method_gaps", [])
    affected_methods = [f"{g['class']}.{g['method']}" for g in method_gaps[:5]]

    # Reasoning
    reasoning = proposal.get("reasoning", "") or proposal.get("expected_benefit", "")

    # Confidence
    confidence = min(1.0, abs(branch_delta) / 5.0)

    # Build principle ID
    pid = f"p_{len(principles) + 1:03d}"

    principle = {
        "id": pid,
        "project": project_name,
        "type": principle_type,
        "round": round_num,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "change_summary": change_summary,
        "coverage_delta": {
            "line": round(line_delta, 2),
            "branch": round(branch_delta, 2),
            "method": round(method_delta, 2),
        },
        "affected_methods": affected_methods,
        "reasoning": reasoning[:300],
        "confidence": round(confidence, 2),
    }

    principles.append(principle)

    # Trim to max 50
    if len(principles) > 50:
        principles = principles[-50:]

    principles_path.parent.mkdir(parents=True, exist_ok=True)
    principles_path.write_text(
        json.dumps({"principles": principles}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"[optimizer] principle {pid} ({principle_type}) distilled, confidence={confidence:.2f}")


# ---------------------------------------------------------------------------
# Existing helper functions (unchanged)
# ---------------------------------------------------------------------------

def render_skill(script_root: Path, skill_pack: Path, skill_output: Path):
    renderer = script_root / "agent" / "skills" / "render_skill.py"
    cmd = [sys.executable, str(renderer), "--pack", str(skill_pack), "--output", str(skill_output)]
    subprocess.run(cmd, check=True)


def run_gate(gate_cmd: str):
    if not gate_cmd:
        return {"executed": False, "exit_code": None}
    result = subprocess.run(gate_cmd, shell=True)
    return {"executed": True, "exit_code": result.returncode}


def rollback_to_pack(root: Path, old_pack: dict, skill_pack_path: Path, skill_output_path: Path):
    skill_pack_path.write_text(json.dumps(old_pack, indent=2, ensure_ascii=False), encoding="utf-8")
    render_skill(root, skill_pack_path, skill_output_path)


def extract_quality(report: dict) -> dict:
    test_execution = report.get("test_execution", {})
    quality = report.get("quality", {})
    pass_rate = test_execution.get("pass_rate_pct")
    try:
        pass_rate = float(pass_rate) if pass_rate is not None else None
    except (TypeError, ValueError):
        pass_rate = None
    return {
        "pass_rate_pct": pass_rate,
        "compile_failed": bool(quality.get("compile_failed", False)),
    }


def evaluate_gate(before_report: dict, after_report: dict, branch_tolerance: float = 0.2, pass_rate_drop_tol: float = 3.0):
    before_total = get_total(before_report)
    after_total = get_total(after_report)
    before_quality = extract_quality(before_report)
    after_quality = extract_quality(after_report)
    reject_reasons = []

    before_branch = float(before_total.get("branch", 0.0))
    after_branch = float(after_total.get("branch", 0.0))
    if after_branch + branch_tolerance < before_branch:
        reject_reasons.append(
            f"branch_drop_exceeded: before={before_branch:.2f} after={after_branch:.2f} tolerance={branch_tolerance:.2f}"
        )

    if not before_quality["compile_failed"] and after_quality["compile_failed"]:
        reject_reasons.append("compile_failure_rate_increased: before=0 after=1")

    before_pass = before_quality["pass_rate_pct"]
    after_pass = after_quality["pass_rate_pct"]
    if before_pass is not None and after_pass is not None:
        if after_pass + pass_rate_drop_tol < before_pass:
            reject_reasons.append(
                f"pass_rate_drop_exceeded: before={before_pass:.2f} after={after_pass:.2f} tolerance={pass_rate_drop_tol:.2f}"
            )

    return {
        "accept": len(reject_reasons) == 0,
        "reject_reasons": reject_reasons,
        "before_total": before_total,
        "after_total": after_total,
        "before_quality": before_quality,
        "after_quality": after_quality,
    }


def reject_with_rollback(
    root: Path,
    old_pack: dict,
    skill_pack_path: Path,
    skill_output_path: Path,
    decision: str,
    reason: str,
    reject_reasons: list,
):
    reject_reasons.append(reason)
    rollback_to_pack(root, old_pack, skill_pack_path, skill_output_path)
    return decision


# ---------------------------------------------------------------------------
# main()
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    root = Path(__file__).resolve().parent.parent
    report_path = Path(args.report)
    feedback_path = Path(args.feedback)
    skill_pack_path = Path(args.skill_pack)
    skill_output_path = Path(args.skill_output)

    if not report_path.exists():
        print(f"[optimizer] ERROR: report not found: {report_path}")
        sys.exit(1)
    if not feedback_path.exists():
        print(f"[optimizer] ERROR: feedback not found: {feedback_path}")
        sys.exit(1)
    if not skill_pack_path.exists():
        print(f"[optimizer] ERROR: skill pack not found: {skill_pack_path}")
        sys.exit(1)

    report = json.loads(report_path.read_text(encoding="utf-8"))
    feedback = json.loads(feedback_path.read_text(encoding="utf-8"))
    pack = json.loads(skill_pack_path.read_text(encoding="utf-8"))
    before_total = get_total(report)

    proposal, next_pack = build_proposal(
        report,
        feedback,
        pack,
        args.round,
        max_step_changes=args.max_step_changes,
        use_llm=args.use_llm,
        model=args.model,
        principles_dir=args.principles_dir,
        cwd=root,
    )
    backup = skill_pack_path.with_suffix(".json.bak")
    backup.write_text(json.dumps(pack, indent=2, ensure_ascii=False), encoding="utf-8")
    skill_pack_path.write_text(json.dumps(next_pack, indent=2, ensure_ascii=False), encoding="utf-8")
    render_skill(root, skill_pack_path, skill_output_path)

    gate = run_gate(args.gate_cmd)
    decision = "accepted"
    after_total = before_total
    reject_reasons = []
    gate_compare = {}
    rolled_back = False

    if not args.gate_cmd:
        decision = reject_with_rollback(
            root,
            pack,
            skill_pack_path,
            skill_output_path,
            "rejected_gate_not_configured",
            "gate_cmd_not_provided",
            reject_reasons,
        )
        rolled_back = True
    elif not args.gate_report:
        decision = reject_with_rollback(
            root,
            pack,
            skill_pack_path,
            skill_output_path,
            "rejected_gate_report_missing",
            "gate_report_path_not_provided",
            reject_reasons,
        )
        rolled_back = True
    else:
        if not gate["executed"]:
            decision = reject_with_rollback(
                root,
                pack,
                skill_pack_path,
                skill_output_path,
                "rejected_gate_not_executed",
                "gate_not_executed",
                reject_reasons,
            )
            rolled_back = True
        elif gate["exit_code"] != 0:
            decision = reject_with_rollback(
                root,
                pack,
                skill_pack_path,
                skill_output_path,
                "rejected_gate_cmd_failed",
                f"gate_cmd_failed: exit_code={gate['exit_code']}",
                reject_reasons,
            )
            rolled_back = True
        else:
            gate_report_path = Path(args.gate_report)
            if not gate_report_path.exists():
                decision = reject_with_rollback(
                    root,
                    pack,
                    skill_pack_path,
                    skill_output_path,
                    "rejected_gate_report_missing",
                    f"gate_report_not_found: {gate_report_path}",
                    reject_reasons,
                )
                rolled_back = True
            else:
                after_report = json.loads(gate_report_path.read_text(encoding="utf-8"))
                gate_compare = evaluate_gate(
                    report,
                    after_report,
                    branch_tolerance=args.branch_drop_tolerance,
                    pass_rate_drop_tol=args.pass_rate_drop_tolerance,
                )
                after_total = gate_compare["after_total"]
                if not gate_compare["accept"]:
                    decision = "rejected_gate_metrics"
                    reject_reasons.extend(gate_compare["reject_reasons"])
                    rollback_to_pack(root, pack, skill_pack_path, skill_output_path)
                    rolled_back = True

    # Distill principle after gate decision
    if args.principles_dir and args.project_name:
        distill_principle(
            proposal=proposal,
            decision=decision,
            before_total=before_total,
            after_total=after_total,
            feedback=feedback,
            round_num=args.round,
            principles_dir=args.principles_dir,
            project_name=args.project_name,
        )

    result = {
        "round": args.round,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "proposal": proposal,
        "before_total": before_total,
        "after_total": after_total,
        "gate": gate,
        "decision": decision,
        "accepted": decision == "accepted",
        "rolled_back": rolled_back,
        "reject_reasons": reject_reasons,
        "gate_compare": gate_compare,
        "backup": str(backup),
    }

    if args.result:
        result_path = Path(args.result)
    else:
        result_path = root / "results" / f"optimizer_round_{args.round}.json"
    result_path.parent.mkdir(parents=True, exist_ok=True)
    result_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"[optimizer] round={args.round} decision={decision} method={proposal.get('method', 'rules')}")
    print(f"[optimizer] result={result_path}")


if __name__ == "__main__":
    main()
